### ISSUE TITLE
CMake Error at CMakeLists.txt

### ISSUE THREAD

**Issue by zhenghaoxd** [skalenetwork/libBLS#101]
Hello,I have a cmake error when I do the following command on Ubuntu 16.04TLS:

> cmake -H. -Bbuild

 and then ,the terminal shows that:

> CMake Error at CMakeLists.txt:10 (message):
  Require at least gcc-7.0

-- Configuring incomplete, errors occurred!

but when I check the gcc version by gcc -v
it shows:

> Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~16.04) 

I think my gcc version have reached this lib, but why I have this error? How can I fix it?

**Comment by olehnikolaiev** [comment]
Hello @zhenghaoxd ! Does your default compiler different from `gcc`? Please check it, maybe you use `clang`. Also, please try `cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -H. -Bbuild`

**Comment by zhenghaoxd** [comment]
Thank you for your reply! 
Inspired by your reply, I changed my symbolic link to gcc-7 and g++-7. Now I can compiler this project successfully! 
Thank you agian, and wish you all the best!
