### ISSUE TITLE
error: missing template arguments before ‘keys’

### ISSUE THREAD

**Issue by zhenghaoxd** [skalenetwork/libBLS#103]
Hello!
When I compile threshold_encryption/TEPrivateKeyShare.cpp, there is a error:

threshold_encryption/TEPrivateKeyShare.cpp: In static member function ‘static std::pair<std::shared_ptr<std::vector<std::shared_ptr<TEPrivateKeyShare> > >, std::shared_ptr<TEPublicKey> > TEPrivateKeyShare::generateSampleKeys(size_t, size_t)’:

threshold_encryption/TEPrivateKeyShare.cpp:128:15: error: missing template arguments before ‘keys’
  128 |     std::pair keys = std::make_pair(
      |               ^~~~
threshold_encryption/TEPrivateKeyShare.cpp:131:12: error: ‘keys’ was not declared in this scope; did you mean ‘skeys’?
  131 |     return keys;

the codes are:

std::pair keys = std::make_pair(
        std::make_shared< std::vector< std::shared_ptr< TEPrivateKeyShare > > >( skey_shares ),
        std::make_shared< TEPublicKey >( common_public ) );
    return keys;

I think the type of variable should be indicated before `keys` .Am I right? Is there any other solution?

**Comment by olehnikolaiev** [comment]
Hello @zhenghaoxd ! What you said will definitely solve the problem but I think it is not the only way and the issue may come from your complier and its options. What compiler do you use? Could you also please provide its version and cmake version as well? Thank you!

**Comment by zhenghaoxd** [comment]
> Hello @zhenghaoxd ! What you said will definitely solve the problem but I think it is not the only way and the issue may come from your complier and its options. What compiler do you use? Could you also please provide its version and cmake version as well? Thank you!

My compiler is g++9.3.0, the os is Ubuntu20.04, and the cmake version is 3.18.0

**Comment by olehnikolaiev** [comment]
@zhenghaoxd looks like this issue caused by g++9, indicating variables' types before `keys` should works. let me know if you have any other difficulties!

**Comment by zhenghaoxd** [comment]
Thanks a lot. 
Could you tell me what the types of `std::make_shared<std::vector< std::shared_ptr< TEPrivateKeyShare > > >( skey_shares )`  and `std::make_shared< TEPublicKey >( common_public ) )`

**Comment by zhenghaoxd** [comment]
Thanks a lot.
Could you please tell me what the types of std::make_shared<std::vector< std::shared_ptr< TEPrivateKeyShare > > >( skey_shares ) and std::make_shared< TEPublicKey >( common_public ) )?

**Comment by zhenghaoxd** [comment]
Thanks a lot.
Could you please tell me what the types of `std::make_shared<std::vector< std::shared_ptr< TEPrivateKeyShare > > >( skey_shares )` and` std::make_shared< TEPublicKey >( common_public ) )`

**Comment by olehnikolaiev** [comment]
`std::pair<std::shared_ptr< std::vector< std::shared_ptr< TEPrivateKeyShare > > >, std::shared_ptr< TEPublicKey >> keys` works for me
