### ISSUE TITLE
error:catching polymorphic type ‘class std::logic_error’ by value [-Werror=catch-value=]

### ISSUE THREAD

**Issue by bo-hub** [skalenetwork/libBLS#129]
Hello！
I am trying to build the project from source.

I have run the following command.

```
sudo apt-get update
sudo apt-get install -y automake cmake build-essential libprocps-dev libtool\
                        pkg-config yasm texinfo autoconf flex bison clang-format-6.0
git clone https://github.com/skalenetwork/libBLS.git
cd libBLS
cd deps
bash ./build.sh
cd ..

cmake -H. -Bbuild
```

Until now , all steps above were done successfully. 
When I run 

```
cmake --build build -- -j$(nproc)
```

It came to the error as the title said:

>....
[ 96%] Linking CXX executable bls_unit_test
[ 96%] Built target bls_unit_test
/home/bob/pkg/libBLS/test/unit_tests_dkg.cpp: In member function ‘void DkgAlgorithm::PolynomialValue::test_method()’:
/home/bob/pkg/libBLS/test/unit_tests_dkg.cpp:64:20: error: catching polymorphic type ‘class std::logic_error’ by value [-Werror=catch-value=]
   64 |     } catch ( std::logic_error ) {
      |                    ^~~~~~~~~~~
[ 98%] Linking CXX executable generate_key_system
[ 98%] Built target generate_key_system
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/dkg_unit_test.dir/build.make:63：CMakeFiles/dkg_unit_test.dir/test/unit_tests_dkg.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:506：CMakeFiles/dkg_unit_test.dir/all] error 2
make: *** [Makefile:141：all] error 2

Seeking help to fix this building error.

### Host operating system
Description:	Ubuntu 20.04.2 LTS

### Compiler information
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-4100)

**Comment by olehnikolaiev** [comment]
hello @bo-hub ! gcc-9 and ubuntu20 are not supported by this project for now. to use gcc-7 for this project you can run export CC=/usr/local/bin/gcc-7
export CXX=/usr/local/bin/g++-7
however, build may crash on ubuntu20 even with gcc-7

**Comment by bo-hub** [comment]
@olehnikolaiev  OK. Thanks for the explanation.

**Comment by kladkogex** [comment]
Reopening since catching exceptions by value is not good

https://stackoverflow.com/questions/62030341/what-is-this-catching-polymorphic-type-x-by-value-wcatch-value

**Comment by kladkogex** [comment]
Hey @bo-hub 

We would like to send you 50 SKL tokens as a bug bounty.

Please send your Metamask address to @JulesTimchenko on Twitter.

Thank you,
Stan
