### ISSUE TITLE
init_alt_bn128_params() 

### ISSUE THREAD

**Issue by zlemon819** [skalenetwork/libBLS#188]
hi, i am interested about your projects for "threshold encryption" implementation, but comes across a question now. Why "init_alt_bn128_params()" was called many times during  whole threshold encryption process. it seems to be a system params setup, which  was generally regarded initialed only once, right? Could you give some explainations.
Thanks.

**Comment by olehnikolaiev** [comment]
hi @zlemon819 ! you are right, in specific application `init_alt_bn128_params()` function can be called only once to make everything work. in fact, this library is used for different purposes so there are more calls ( we cannot have only one `init_alt_bn128_params()` call for all dkg proccess, bls signatures and threshold encryption ).
