### ISSUE TITLE
serialing TEPrivatekeyShare and TEPublickeyShare

### ISSUE THREAD

**Issue by zlemon819** [skalenetwork/libBLS#189]
hi, i found the "toString" function in TEPrivateKeyShare and TEPublicKeyShare only encodes the PublicKey and PrivateKey, leaving alone other arguments "SignedTx, requiredSigners and requiredSigners". If i want to recover a TEPrivatekeyshare directly from bytes, could you give a complete function which will encode the entire arguments.

Thank you.

**Comment by olehnikolaiev** [comment]
hi @zlemon819 ! in `tools/decryptMessage.cpp` there is an example of decrypting message from string that requires private key access. there is no function that deserializes bytes to `TEPrivateKeyShare` / `TEPublicKeyShare` object but there are functions that create `libff::alt_bn128_Fr` or `libff::alt_bn128_G2` from string ( then you can create corresponding `TEKeyShare` objects using your code)

**Comment by zlemon819** [comment]
> hi @zlemon819 ! in `tools/decryptMessage.cpp` there is an example of decrypting message from string that requires private key access. there is no function that deserializes bytes to `TEPrivateKeyShare` / `TEPublicKeyShare` object but there are functions that create `libff::alt_bn128_Fr` or `libff::alt_bn128_G2` from string ( then you can create corresponding `TEKeyShare` objects using your code)

thank you, i will try that, but i have come across another question. I found there exists no "G1ToString", but only exists "G1ToString“, could you guide  how to do this?

**Comment by zlemon819** [comment]
> hi @zlemon819 ! in `tools/decryptMessage.cpp` there is an example of decrypting message from string that requires private key access. there is no function that deserializes bytes to `TEPrivateKeyShare` / `TEPublicKeyShare` object but there are functions that create `libff::alt_bn128_Fr` or `libff::alt_bn128_G2` from string ( then you can create corresponding `TEKeyShare` objects using your code)

thank you, i will try that, but i have come across another question. I found that there exists "G2ToString” and "stringToG2" for serializing and deserializing G2 point, but only exists "stringToG1" for G1 deserializing,  how should i serialize a G1 point to string, can you privide the missing "G1ToString"?
