### ISSUE TITLE
Support of Ubuntu 20.04

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/libBLS#197]
* PRD: SYSTEM UPGRADE
* **Warning**: Github Actions will drop Ubuntu 18.04 runner on April 1st (https://github.com/actions/runner-images/issues/6002), which will affect both development and testing.

We need to update libbls to ubuntu 20.04 as it is a part of sgxwallet. Need to:
- Verify its compatibility with ubuntu 20.04 and 18.04
- Fix incompatibilities if presented
- Update CI to use ubuntu 20.04

**Comment by DmytroNazarenko** [comment]
No QA

**Comment by OleksanderSalamatov** [comment]
Not for QA testing
