### ISSUE TITLE
CMAKE error 

### ISSUE THREAD

**Issue by einai** [skalenetwork/libBLS#35]
I got a problem when I "cmake --build build -- -j$(nproc)" in ubuntu.

the error msgs are 
"
[  1%] Building CXX object libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o
cc1plus: error: -Werror=int-in-bool-context: no option -Wint-in-bool-context
libff/depends/CMakeFiles/zm.dir/build.make:62: recipe for target 'libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o' failed
make[2]: *** [libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o] Error 1
CMakeFiles/Makefile2:666: recipe for target 'libff/depends/CMakeFiles/zm.dir/all' failed
make[1]: *** [libff/depends/CMakeFiles/zm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
"

What can I do for it?

**Comment by DimaStebaev** [comment]
Hello @einai.

What C++ compiler do you use?

**Comment by einai** [comment]
Sorry, I couldn't be aware of your reply.
I set c++ compiler to g++.

The error was raised up on Ubuntu 64 bit.
So I tried 32 bit again, and I got another error (exaclty endless loop).

What C++ compiler do I have to use?
-------------------- The error is below -------------------
CMake Warning (dev) at libff/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

-- GMP: /home/libBLS/libBLS/build/deps/lib/libgmp.a, /home/libBLS/libBLS/build/deps/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libprocps'
--   Found libprocps, version 3.3.10
INFO - Using final BLS INC=/home/libBLS/libBLS/libff
INFO - Using final BLS LIB=/home/libBLS/libBLS/build/libff/libff
CMake Warning (dev) at CMakeLists.txt:104 (set):
  Cannot set "BLS_INCLUDE_DIRS": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++
CMAKE_CXX_COMPILER= /usr/bin/c++

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
CMake Warning (dev) at libff/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

-- GMP: /home/libBLS/libBLS/build/deps/lib/libgmp.a, /home/libBLS/libBLS/build/deps/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libprocps'
--   Found libprocps, version 3.3.10
INFO - Using final BLS INC=/home/libBLS/libBLS/libff
INFO - Using final BLS LIB=/home/libBLS/libBLS/build/libff/libff
CMake Warning (dev) at CMakeLists.txt:104 (set):
  Cannot set "BLS_INCLUDE_DIRS": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++
CMAKE_CXX_COMPILER= /usr/bin/c++

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
CMake Warning (dev) at libff/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

**Comment by DimaStebaev** [comment]
We use C++17 so you need at least GCC 7.

**Comment by einai** [comment]
Can you tell me your environment when you compiled this? 

I tried to compiled this in Ubuntu 32, 64 both.
And upgrade the compiler too As you said.
Now My compiler version is 

root@k-VirtualBox:/home/libBLS# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
& 
cmake version 3.11.0

Do I have something that I missed?

**Comment by olehnikolaiev** [comment]
@einai Please, check both `gcc` and `g++` versions are at least 7.0.0. Also, could you send us a full cmake log so we can investigate your problem?

**Comment by einai** [comment]
My gcc & g++ versions are below.
root@k-VirtualBox:/home/libBLS# g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@k-VirtualBox:/home/libBLS# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and my error in ubuntu 32bit 

root@k-VirtualBox:/home/libBLS# cmake -H. -Bbuild
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
CMake Warning (dev) at libff/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

-- GMP: /home/libBLS/build/deps/lib/libgmp.a, /home/libBLS/build/deps/include
INFO - Using final BLS INC=/home/libBLS/libff
INFO - Using final BLS LIB=/home/libBLS/build/libff/libff
CMake Warning (dev) at CMakeLists.txt:108 (set):
  Cannot set "BLS_INCLUDE_DIRS": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/libBLS/build
root@k-VirtualBox:/home/libBLS# cmake --build build -- -j$(nproc)
[  1%] Building CXX object libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o
In file included from /home/libBLS/libff/depends/ate-pairing/include/bn.h:12:0,
                 from /home/libBLS/libff/depends/ate-pairing/src/zm2.cpp:12:
/home/libBLS/libff/depends/ate-pairing/include/zm2.h: In static member function ‘static void mie::Fp::fast_modp(mie::Fp&)’:
/home/libBLS/libff/depends/ate-pairing/include/zm2.h:233:27: warning: right shift count >= width of type [-Wshift-count-overflow]
   uint64_t t = z.v_[3] >> 61;
                           ^~
/home/libBLS/libff/depends/ate-pairing/src/zm2.cpp: In static member function ‘static void mie::Fp::setModulo(const Vuint&, int, bool, bool)’:
/home/libBLS/libff/depends/ate-pairing/src/zm2.cpp:3644:22: error: ‘Xbyak’ was not declared in this scope
   static std::vector<Xbyak::uint8> buf;
                      ^~~~~
compilation terminated due to -Wfatal-errors.
libff/depends/CMakeFiles/zm.dir/build.make:86: recipe for target 'libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o' failed
make[2]: *** [libff/depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o] Error 1
CMakeFiles/Makefile2:666: recipe for target 'libff/depends/CMakeFiles/zm.dir/all' failed
make[1]: *** [libff/depends/CMakeFiles/zm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2


thank you.

**Comment by olehnikolaiev** [comment]
@einai did you clone the repo with `--recursive` flag?

**Comment by einai** [comment]
Yes. I checked it. The submodule was downloaded.

root@k-VirtualBox:/home/libBLS/libff# ls
AUTHORS  CMakeLists.txt  depends  libff  LICENSE  README.md
root@k-VirtualBox:/home/libBLS/libff# cd depends/
root@k-VirtualBox:/home/libBLS/libff/depends# ls
ate-pairing  CMakeLists.txt  xbyak
root@k-VirtualBox:/home/libBLS/libff/depends# cd xbyak/
root@k-VirtualBox:/home/libBLS/libff/depends/xbyak# ls
CMakeLists.txt  COPYRIGHT  gen  Makefile  readme.md  readme.txt  sample  test  xbyak  xbyak.sln
root@k-VirtualBox:/home/libBLS/libff/depends/xbyak# cd xbyak
root@k-VirtualBox:/home/libBLS/libff/depends/xbyak/xbyak# ls
xbyak_bin2hex.h  xbyak.h  xbyak_mnemonic.h  xbyak_util.h

**Comment by kladkogex** [comment]
Currently we do not support Linux 32-bit.  If you want to provide a fix, we will incorporate this into the codebase.

**Comment by olehnikolaiev** [comment]
@einai you still can build libBLS on Linux 64-bit. All you need is GCC && G++ version 7+ and all the  required dependencies listed in README
