### ISSUE TITLE
glibtool is not a valid brew package

### ISSUE THREAD

**Issue by mmathys** [skalenetwork/libBLS#91]
**Describe the bug**

As dependency, `glibtool` is noted in `README.md`. However, it doesn't exist in brew. Did you mean `libtool`?

**To Reproduce**
1\. Install dependencies by ```brew install flex bison glibtool automake cmake pkg-config yasm```
2\. See error: `glibtool` is not found.

**Expected behavior**
Package should be installed without an error

**Environment:**

-   MacOS 10.15.3

**Comment by olehnikolaiev** [comment]
@mmathys thank you for finding a typo!
close the issue because the bug was fixed
